/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./views/**/*.{ejs,html}",   // ✅ Scan your EJS templates
    "./public/**/*.js",          // ✅ Scan any JS files in public
    "./routes/**/*.js"           // ✅ Optional, if you use Tailwind in templates generated by routes
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
